CREATE TABLE NGUOIDUNG (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TEN NVARCHAR (50) NOT NULL,
    EMAIL NVARCHAR (50) NOT NULL,
    PASS NVARCHAR (50) NOT NULL,
    PHONE INT NOT NULL,
    ADDRESS NVARCHAR (50) NOT NULL,
    TYPE BOOLEAN NOT NULL,
    STATUS BOOLEAN NOT NULL
);

CREATE TABLE DANHMUC (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TENDANHMUC NVARCHAR (50) NOT NULL
);

CREATE TABLE CHITIET (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DUNGLUONG NVARCHAR (50) NOT NULL,
    ANH NVARCHAR (50) NOT NULL,
    MOTA NVARCHAR (500) NOT NULL
);

CREATE TABLE SANPHAM (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TEN NVARCHAR (50) NOT NULL,
    CHITIETSP INT NOT NULL,
    DANHMUCSP INT NOT NULL,
    CONSTRAINT CHITIET FOREIGN KEY (CHITIETSP) REFERENCES CHITIET (ID),
    CONSTRAINT DANHMUC FOREIGN KEY (DANHMUCSP) REFERENCES DANHMUC (ID)
);

SELECT
    *
FROM
    SANPHAM SP
    INNER JOIN DANHMUC DM ON SP.ID = DM.ID
    INNER JOIN CHITIET CT ON CT.ID = SP.ID